'use client';

/**
 * Interactive parts of the story page (likes, comments, owner controls).
 * Split out of page.tsx so the page itself can be a SERVER component that
 * exports generateMetadata() for SEO/OG tags. This client component still
 * fetches the full post (for per-viewer like/bookmark flags + owner checks).
 */
import { getPostById, Post } from '@/services/postService';
import React, { useState, useEffect } from 'react';
import PostActions from '@/components/common/PostActions';
import CommentList from '@/components/common/CommentList';
import InteractionButtons from '@/components/common/InteractionButtons';
import RegenerateWithFeedback from '@/components/story/RegenrateWithFeedback';
import PublishControls from '@/components/story/PublishControls';
import DOMPurify from 'isomorphic-dompurify';
import Link from 'next/link';
import { useHydratedAuth } from '@/hooks/useHydratedAuth';
import AdSlot from '@/components/ads/AdSlot';

export default function StoryDetailClient({ postId }: { postId: string }) {
  const [post, setPost] = useState<Post | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const { user, isAuthenticated, isHydrated } = useHydratedAuth();

  useEffect(() => {
    if (!postId) return;
    let cancelled = false;
    (async () => {
      try {
        const postData = await getPostById(postId);
        if (!cancelled) setPost(postData);
      } catch {
        if (!cancelled) setError('Story not found or you do not have permission to view it.');
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => { cancelled = true; };
  }, [postId]);

  const canModify =
    isHydrated &&
    isAuthenticated && post !== null &&
    (
      user?.id === post.user?.id ||
      ['moderator', 'superadmin'].includes(user?.role?.name ?? '')
    );

  if (loading) return <p className="p-8 text-center">Loading post...</p>;
  if (error) return <p className="p-8 text-center text-red-500">{error}</p>;
  if (!post) return <p className="p-8 text-center">Story not found.</p>;

  return (
    <main className="mx-auto max-w-3xl p-8 font-sans">
      <article>
        <h1 className="mb-4 text-4xl font-bold text-text">{post.title}</h1>

        <AdSlot className="my-6" />

        <PostActions
          postAuthorId={post.user?.id ?? ''}
          postId={post.id}
          isAI={post.source === 'ai'}
        />
        <div className="mb-8 text-sm text-text-light">
          <span>By {post.user?.username ?? 'Unknown'}</span>
          <span className="mx-2">•</span>
          <span>{new Date(post.created_at).toLocaleDateString()}</span>
        </div>

        <AdSlot className="my-6" />

        <div
          className="prose lg:prose-xl text-text"
          dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(post.content || '') }}
        />

        <div className="mb-4 flex flex-wrap gap-2">
          {(post.tags ?? []).map((tag) => (
            <Link
              href={`/tags/${tag.name}`}
              key={tag.id}
              className="text-sm font-medium bg-primary/10 text-primary px-2 py-1 rounded-full hover:bg-primary hover:text-white transition-colors"
            >
              #{tag.name}
            </Link>
          ))}
        </div>
      </article>

      {post.source === 'ai' && (
        <div className="mb-4 text-sm text-gray-600">
          <div>Generated by AI • version {post.version ?? 1}</div>
          <div>
            Genre: {post.genre || '—'} | Tone: {post.tone || '—'} | Length: {post.length_label || '—'}
          </div>
        </div>
      )}
      {canModify && <PublishControls postId={post.id} isPublished={post.is_published} />}
      {post.source === 'ai' && canModify && (
        <div className="mt-8">
          <RegenerateWithFeedback postId={post.id} />
        </div>
      )}

      <AdSlot className="my-8" />

      <div className="mt-8 border-t pt-4">
        <InteractionButtons
          postId={post.id}
          initialLiked={post.is_liked_by_user}
          initialBookmarked={post.is_bookmarked_by_user}
        />
      </div>

      <CommentList postId={postId} />
    </main>
  );
}
