"""changing db model

Revision ID: 2b6b2eed2452
Revises: 655d1dfe1126
Create Date: 2025-10-18 19:21:29.628705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6b2eed2452'
down_revision: Union[str, None] = '655d1dfe1126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'click_count')
    op.drop_column('ads', 'tags')
    op.add_column('error_logs', sa.Column('error_hash', sa.String(length=64), nullable=False))
    op.add_column('error_logs', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('error_logs', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('error_logs', sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_error_logs_error_hash'), 'error_logs', ['error_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_logs_error_hash'), table_name='error_logs')
    op.drop_column('error_logs', 'first_seen_at')
    op.drop_column('error_logs', 'last_seen_at')
    op.drop_column('error_logs', 'count')
    op.drop_column('error_logs', 'error_hash')
    op.add_column('ads', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('click_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
