"""Initial schema from models

Revision ID: 2b716709d6dd
Revises: 
Create Date: 2025-10-10 05:09:14.676191

"""
from typing import Sequence, Union
from passlib.context import CryptContext
from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision: str = '2b716709d6dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_creator_requests_status'), 'creator_requests', ['status'], unique=False)
    op.add_column('notifications', sa.Column('target_id_uuid', sa.UUID(), nullable=True))
    op.execute(
        'UPDATE notifications SET target_id_uuid = gen_random_uuid() WHERE target_id IS NOT NULL'
    )
    op.drop_column('notifications', 'target_id')
    op.alter_column('notifications', 'target_id_uuid', new_column_name='target_id')
    
    users_table = sa.table(
        'users',
        sa.column('id', sa.UUID),
        sa.column('email', sa.String),
        sa.column('username', sa.String),
        sa.column('password_hash', sa.String),
        sa.column('role_id', sa.UUID),
        sa.column('is_verified', sa.Boolean)
        # Add other non-nullable columns with default values if they exist in your model
    )

    # Generate a secure, random password hash. This user will never log in,
    # but the field cannot be empty.
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    automod_password_hash = pwd_context.hash(str(uuid.uuid4()))

    op.bulk_insert(users_table, [
        {
            'id': str(uuid.uuid4()),
            'email': 'automod@system.local',
            'username': 'automod', # This unique username is how we will find the user
            'password_hash': automod_password_hash,
            'role_id': "efc422f1-dc73-46f4-9464-c9208461621d", # Assign the role ID we generated above
            'is_verified': True # System users should be pre-verified
        }
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('notifications', sa.Column('target_id_int', sa.Integer(), nullable=True))
    # Note: A real downgrade would need a way to convert UUIDs back to integers, which is complex.
    # For now, we'll just set them to null.
    op.execute('UPDATE notifications SET target_id_int = NULL')
    op.drop_column('notifications', 'target_id')
    op.alter_column('notifications', 'target_id_int', new_column_name='target_id')

    op.drop_index(op.f('ix_creator_requests_status'), table_name='creator_requests')
    op.drop_table('creator_requests')
    # ### end Alembic commands ###
