"""empty message

Revision ID: 52a01f6c0721
Revises: 2197b9d7fa39
Create Date: 2025-07-21 03:47:49.730088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a01f6c0721'
down_revision: Union[str, None] = '2197b9d7fa39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_deleted_at'), 'posts', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_deleted_at'), table_name='posts')
    op.drop_column('posts', 'deleted_at')
    # ### end Alembic commands ###
