"""Add all new models and ip_address column

Revision ID: aca417717944
Revises: 673ab112818b
Create Date: 2025-07-20 16:09:22.792041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca417717944'
down_revision: Union[str, None] = '673ab112818b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view_history', sa.Column('ip_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view_history', 'ip_address')
    # ### end Alembic commands ###
