"""Add all new models and ip_address column

Revision ID: b6b3a5667a2c
Revises: aca417717944
Create Date: 2025-07-20 16:12:48.747434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b3a5667a2c'
down_revision: Union[str, None] = 'aca417717944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view_history', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view_history', 'user_agent')
    # ### end Alembic commands ###
